CREATE TABLE IF NOT EXISTS menus (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  is_addon BOOLEAN NOT NULL DEFAULT 0,

  FOREIGN KEY (category_id) REFERENCES categories(id)
);
